# Generated by Django 5.1.1 on 2025-07-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Operator', 'Operator'), ('Finisher', 'Finisher'), ('Admin', 'Admin'), ('Management', 'Management'), ('Accountant', 'Accountant'), ('Graphics', 'Graphics'), ('Security', 'Security')], max_length=20, null=True),
        ),
    ]
