# Generated by Django 5.1.1 on 2025-07-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='next_of_kin_contact',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
