# Generated by Django 5.1.1 on 2025-07-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_photo_customuser_staff_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='staff_image',
            new_name='photo',
        ),
    ]
