# Generated by Django 5.1.1 on 2025-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_salary_balance_salary_loan_salary_payment_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
