# Generated by Django 5.1.1 on 2025-07-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_staff_image_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Home Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='next_of_kin_contact',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Next of Kin Contact Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, verbose_name='Staff Phone Contact'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='Staff Image'),
        ),
    ]
