# Generated by Django 5.1.1 on 2025-07-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayment_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_repayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_repayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
