# Generated by Django 5.1.1 on 2025-08-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_loan_repayment_end_date_loan_total_repayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='payment_for',
        ),
    ]
